package com.miniapp.core.domain.moviedetailmodel

data class MovieDetailDomainModel(
    val originalLanguage: String,
    val imdbId: String,
    val video: Boolean,
    val title: String,
    val backdropPath: String,
    val revenue: Long,
    val genresName: List<String?>,
    val genresId: List<Int?>,
    val popularity: Double,
    val productionCountriesCode: List<String?>,
    val productionCountriesName: List<String?>,
    val id: Int,
    val voteCount: Int,
    val budget: Int,
    val overview: String,
    val originalTitle: String,
    val runtime: Int,
    val posterPath: String,
    val spokenLanguagesCode: List<String?>,
    val spokenLanguagesName: List<String?>,
    val productionCompaniesLogo: List<String?>,
    val productionCompaniesName: List<String?>,
    val productionCompaniesId: List<Int?>,
    val productionCompaniesCountries: List<String?>,
    val releaseDate: String,
    val voteAverage: Double,
    val tagline: String,
    val adult: Boolean,
    val homepage: String,
    val status: String,
    val favourite: Boolean
)
